// Code generated by generate.go using go generate. DO NOT EDIT.
// Generated at
//  {{ .Timestamp }}
// using data from
// {{ .URLs }}

package main

import "github.com/acohn/ct-accepted-roots/loglist/schema"

var Logs = []schema.Log{}
