// Code generated by log_list_gen.go using go generate. DO NOT EDIT.
// Generated at
//  Wed, 12 Feb 2020 17:03:15 UTC
// using data from
//  https://crt.sh/logs.json
//  https://www.gstatic.com/ct/log_list/all_logs_list.json
//  https://raw.githubusercontent.com/acohn/ct-accepted-roots/master/loglist/all_logs.json

package loglist

import "time"

var Timestamp = time.Date(2020, time.February, 12, 17, 3, 15, 0, time.UTC)

var Logs = LogList{
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEK9Y56IP6DGQy2d9moYGJChZPoktXoYwaG0MBN/4X5MSFmBaYJfNm3mCwzLVefkjh2wz8Q6q2S75hS/OeHGiZUg==",
		Description:       "Google 'Solera2023' log", // +X6XuNM+96FZAqU6GeF5kOXcQGoDGCW6rZPpj5ucacs=
		Url:               "ct.googleapis.com/logs/solera2023",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVG18id3qnfC6X/RtYHo3TwIlvxz2b4WurxXfaW7t26maKZfymXYe5jNGHif0vnDdWde6z/7Qco6wVw+dN4liow==",
		Description:       "Google 'Argon2017' log", // +tTJfMSe4vishcXqXOoJ0CINu/TknGtQZi/4aPhrjCg=
		Url:               "ct.googleapis.com/logs/argon2017",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEX+0nudCKImd7QCtelhMrDW0OXni5RE10tiiClZesmrwUk2iHLCoTHHVV+yg5D4n/rxCRVyRhikPpVDOLMLxJaA==",
		Description:       "DigiCert Nessie 2019", // /kRhCLHQGreKYsz+q2qysrq/86va2ApNizDfLQAIgww=
		Url:               "nessie2019.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELPXCMfVjQ2oWSgrewu4fIW4Sfh3lco90CwKZ061pvAI1eflh6c8ACE90pKM0muBDHCN+j0HV7scco4KKQPqq4A==",
		Description:       "Comodo 'Dodo' CT log", // 23b9raxl59CVCIhuIVm9i5A1L1/q0+PcXiLrNQrMe5g=
		Url:               "dodo.ct.comodo.com",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhjyxDVIjWt5u9sB/o2S8rcGJ2pdZTGA8+IpXhI/tvKBjElGE5r3de4yAfeOPhqTqqc+o7vPgXnDgu/a9/B+RLg==",
		Description:       "Let's Encrypt Oak 2022", // 36Veq2iCTx9sre64X04+WurNohKkal6OOxLAIERcKnM=
		Url:               "oak.ct.letsencrypt.org/2022",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEkZd/ow8X+FSVWAVSf8xzkFohcPph/x6pS1JHh7g1wnCZ5y/8Hk6jzJxs6t3YMAWz2CPd4VkCdxwKexGhcFxD9A==",
		Description:       "DigiCert Yeti 2019", // 4mlLribo6UAJ6IYbtjuD1D7n/nSI+6SPKJMBnd3x2/4=
		Url:               "yeti2019.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfzb42Zdr/h7hgqgDCo1vrNJqGqbcUvJGJEER9DDqp19W/wFSB0l166hD+U5cAXchpH8ZkBNUuvOHS0OnJ4oJrQ==",
		Description:       "Let's Encrypt Oak 2020", // 5xLysDd+GmL7jskMYYTx6ns3y1YdESZb8+DzS/JBVG4=
		Url:               "oak.ct.letsencrypt.org/2020",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0JCPZFJOQqyEti5M8j13ALN3CAVHqkVM4yyOcKWCu2yye5yYeqDpEXYoALIgtM3TmHtNlifmt+4iatGwLpF3eA==",
		Description:       "Google 'Argon2023' log", // 6D7Q2j71BjUy51covIlryQPTy9ERa+zraeF3fW0GvW4=
		Url:               "ct.googleapis.com/logs/argon2023",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIFsYyDzBi7MxCAC/oJBXK7dHjG+1aLCOkHjpoHPqTyghLpzA9BYbqvnV16mAw04vUjyYASVGJCUoI3ctBcJAeg==",
		Description:       "Google 'Rocketeer' log", // 7ku9t3XOYLrhQmkfq+GeZqMPfl+wctiDAMR7iXqo/cs=
		Url:               "ct.googleapis.com/rocketeer",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE9o7AiwrbGBIX6Lnc47I6OfLMdZnRzKoP5u072nBi6vpIOEooktTi1gNwlRPzGC2ySGfuc1xLDeaA/wSFGgpYFg==",
		Description:       "DigiCert Nessie 2021", // 7sCV7o1yZA+S48O5G8cSo2lqCXtLahoUOOZHssvtxfk=
		Url:               "nessie2021.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEURAG+Zo0ac3n37ifZKUhBFEV6jfcCzGIRz3tsq8Ca9BP/5XUHy6ZiqsPaAEbVM0uI3Tm9U24RVBHR9JxDElPmg==",
		Description:       "DigiCert Yeti 2020", // 8JWkWfIA0YJAEC0vk4iOrUv+HUfjmeHQNKawqKqOsnM=
		Url:               "yeti2020.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETeBmZOrzZKo4xYktx9gI2chEce3cw/tbr5xkoQlmhB18aKfsxD+MnILgGNl0FOm0eYGilFVi85wLRIOhK8lxKw==",
		Description:       "Google 'Argon2021' log", // 9lyUL9F3MCIUVBgIMJRWjuNNExkzv98MLyALzE7xZOM=
		Url:               "ct.googleapis.com/logs/argon2021",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZU75VqjyzSTgFZKAnWg1QeYfFFIRZTMK7q3kWWZsmHhQdrBYnHRZ3OA4kUeUx0JN+xX+dSgt1ruqUhhl7jOvmw==",
		Description:       "Google 'Xenon2020' log", // B7dcG+V9aP/xsMYdIxXHuuZXfFeUt2ruvGE6GmnTohw=
		Url:               "ct.googleapis.com/logs/xenon2020",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJUwGinXUWVNaBiK2Vl/rdyMkxKaWJHR8dj9yD5AlZEtEbfvAMQQ8o7DQyXVm7TX+eAA9wL2Vtt6DpoMEL0q/rw==",
		Description:       "Google 'Solera2019' log", // C3YOmouaaC+ImFsV6UdQGlZEa7qIMHhcOEKZQ4ZFDAA=
		Url:               "ct.googleapis.com/logs/solera2019",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/XyDwqzXL9i2GTjMYkqaEyiRL0Dy9sHq/BTebFdshbvCaXXEh6mjUK0Yy+AsDcI4MpzF1l7Kded2MD5zi420gA==",
		Description:       "Google 'Xenon2019' log", // CEEUmABxUywWGQRgvPxH/cJlOvopLHKzf/hjrinMyfA=
		Url:               "ct.googleapis.com/logs/xenon2019",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiKfWtuoWCPMEzSKySjMjXpo38WOdZr6Yq0WYa2JQOv1uVMxkqHywf9Gz1kGeRLq/Rz3tVVvXgqb4jQ1UqKVKnw==",
		Description:       "Google 'Solera2020' log", // H8cs5aG3mfQAw1m/+WyjkTVI6GRCIGEJUum6F3T3usc=
		Url:               "ct.googleapis.com/logs/solera2020",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbgwcuu4rakGFYB17fqsILPwMCqUIsz7VcCTRbR0ttrfzizbcI02VYxK75IaNzOnR7qFAot8LowYKMMqNrKQpVg==",
		Description:       "Google 'Daedalus' log", // HQJLjrFJizRN/YfqPvwJlvdQbyNdHUlwYaR3PEOcJfs=
		Url:               "ct.googleapis.com/daedalus",
		MaximumMergeDelay: 604800,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEn/jYHd77W1G1+131td5mEbCdX/1v/KiYW5hPLcOROvv+xA8Nw2BDjB7y+RGyutD2vKXStp/5XIeiffzUfdYTJg==",
		Description:       "DigiCert Yeti 2022", // IkVFB1lVJFaWP6Ev8fdthuAjJmOtwEt/XcaDXG7iDwI=
		Url:               "yeti2022.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETtK8v7MICve56qTHHDhhBOuV4IlUaESxZryCfk9QbG9co/CqPvTsgPDbCpp6oFtyAHwlDhnvr7JijXRD9Cb2FA==",
		Description:       "Google 'Icarus' log", // KTxRllTIOWW6qlD8WAfUt2+/WHopctykwwz05UVH9Hg=
		Url:               "ct.googleapis.com/icarus",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEeIPc6fGmuBg6AJkv/z7NFckmHvf/OqmjchZJ6wm2qN200keRDg352dWpi7CHnSV51BpQYAj1CQY5JuRAwrrDwg==",
		Description:       "Google 'Argon2022' log", // KXm+8J45OSHwVnOfY6V35b5XfZxgCvj5TV0mXCVdx4Q=
		Url:               "ct.googleapis.com/logs/argon2022",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfQ0DsdWYitzwFTvG3F4Nbj8Nv5XIVYzQpkyWsU4nuSYlmcwrAp6m092fsdXEw6w1BAeHlzaqrSgNfyvZaJ9y0Q==",
		Description:       "DigiCert Yeti 2023", // Nc8ZG7+xbFe/D61MbULLu7YnICZR6j/hKu+oA8M71kw=
		Url:               "yeti2023.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8U+38Y71ejmKupjvqEtlawxXTfXF7igMV8I8vKjj06C+OcfQwP/cv4XCJZxm+gm+zzHWhdEJRVDDwcE8Z2HSmg==",
		Description:       "Cloudflare Cirrus", // ORpT9vlZkgxya++m6eVhlRlIazWCHo6bP8qCGYmzoW8=
		Url:               "ct.cloudflare.com/logs/cirrus",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESLJHTlAycmJKDQxIv60pZG8g33lSYxYpCi5gteI6HLevWbFVCdtZx+m9b+0LrwWWl/87mkNN6xE0M4rnrIPA/w==",
		Description:       "Cloudflare Nimbus 2022", // QcjKsd8iRkoQxqE6CUKHXk4xixsD6+tLx2jwkGKWBvY=
		Url:               "ct.cloudflare.com/logs/nimbus2022",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAExpon7ipsqehIeU1bmpog9TFo4Pk8+9oN8OYHl1Q2JGVXnkVFnuuvPgSo2Ep+6vLffNLcmEbxOucz03sFiematg==",
		Description:       "Cloudflare 'Nimbus2021' Log", // RJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gag=
		Url:               "ct.cloudflare.com/logs/nimbus2021",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEeUeY0SDoUdASOMgFwOFUSkaZ8NoKnknjtbakmBDUJJhPVn9L/adnExZBXl46ZBT701qUixfqd/s3BpuMyWWUdw==",
		Description:       "TrustAsia CT Log", // RTWUmNk6ieAoAwjTfWJtxCN1R1jc4DcANvurDt+Ka88=
		Url:               "ct.trustasia.com/log1",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+WS9FSxAYlCVEzg8xyGwOrmPonoV14nWjjETAIdZvLvukPzIWBMKv6tDNlQjpIHNrUcUt1igRPpqoKDXw2MeKw==",
		Description:       "Google 'Xenon2022' log", // RqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUc=
		Url:               "ct.googleapis.com/logs/xenon2022",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJyTdaAMoy/5jvg4RR019F2ihEV1McclBKMe2okuX7MCv/C87v+nxsfz1Af+p+0lADGMkmNd5LqZVqxbGvlHYcQ==",
		Description:       "DigiCert Nessie 2022", // UaOw9f0BeZxWbbg3eI8MpHrMGyfL956IQpoN/tSLBeU=
		Url:               "nessie2022.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEuFqn5cy1nACARlWIUjeJaRDKl0mcf9gvFZXpPhHsyykizXvULF5GZNGfucWIyUccBRfmYJZTTrXqw0mVts7hA==",
		Description:       "Google 'Solera2018' log", // UutLIl7IlpdIUGdfI+Q7wdAh4yFM5S7NX6h8IDzfygM=
		Url:               "ct.googleapis.com/logs/solera2018",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8m/SiQ8/xfiHHqtls9m7FyOMBg4JVZY9CgiixXGz0akvKD6DEL8S0ERmFe9U4ZiA0M4kbT5nmuk3I85Sk4bagA==",
		Description:       "Comodo 'Sabre' CT log", // VYHUwhaQNgFK6gubVzxT8MDkOHhwJQgXL6OqHQcT0ww=
		Url:               "sabre.ct.comodo.com",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEAkbFvhu7gkAW6MHSrBlpE1n4+HCFRkC5OLAjgqhkTH+/uzSfSl8ois8ZxAD2NgaTZe1M9akhYlrYkes4JECs6A==",
		Description:       "DigiCert Log Server", // VhQGmi/XwuzT9eG9RLI+x0Z2ubyZEVzA75SYVdaJ0N0=
		Url:               "ct1.digicert-ct.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6J4EbcpIAl1+AkSRsbhoY5oRTj3VoFfaf1DlQkfi7Rbe/HcjfVtrwN8jaC+tQDGjF+dqvKhWJAQ6Q6ev6q9Mew==",
		Description:       "DigiCert Yeti 2021", // XNxDkv7mq0VEsV6a1FbmEDf71fpH3KFzlLJe5vbHDso=
		Url:               "yeti2021.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE01EAhx4o0zPQrXTcYjgCt4MVFsT0Pwjzb1RwrM0lhWDlxAYPP6/gyMCXNkOn/7KFsjL7rwk78tHMpY8rXn8AYg==",
		Description:       "Cloudflare 'Nimbus2020' Log", // Xqdz+d9WwOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVg=
		Url:               "ct.cloudflare.com/logs/nimbus2020",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEI3MQm+HzXvaYa2mVlhB4zknbtAT8cSxakmBoJcBKGqGwYS0bhxSpuvABM1kdBTDpQhXnVdcq+LSiukXJRpGHVg==",
		Description:       "Google 'Argon2019' log", // Y/Lbzeg7zCzPC3KEJ1drM6SNYXePvXWmOLHHaFRL2I0=
		Url:               "ct.googleapis.com/logs/argon2019",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFkqNKRuZ+Z8IOsnNJrUZ8gwp+KKGOdQrJ/HKhSadK/SJuoCc9+dxQ7awpmWIMr9SKcQeG5uRzG1kVSyFN4Wfcw==",
		Description:       "Let's Encrypt Oak 2019", // ZZszUPQ7EsxepatOx2XT/ebIgkN3d3jnIAP56yuMMSk=
		Url:               "oak.ct.letsencrypt.org/2019",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEFWj6UQDxzHWmgzQtQQ7REDC0nxnU9mpOmA0lv5trA0t7IRzSkh4DOznPe+nkxmaC8iS1capCtKjyYhUNRrvWqA==",
		Description:       "Google 'Solera2022' log", // aXqvyhprU2+uISBQRt661+Dq6hPSQy5unY+zefK5qvM=
		Url:               "ct.googleapis.com/logs/solera2022",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVqpLa2W+Rz1XDZPBIyKJO+KKFOYZTj9MpJWnZeFUqzc5aivOiWEVhs8Gy2AlH3irWPFjIZPZMs3Dv7M+0LbPyQ==",
		Description:       "DigiCert Nessie 2018", // b/FBtWR+QiL37wUs7658If1gjifSr1pun0uKN9ZjPuU=
		Url:               "nessie2018.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7+R9dC4VFbbpuyOL+yy14ceAmEf7QGlo/EmtYU6DRzwat43f/3swtLr/L8ugFOOt1YU/RFmMjGCL17ixv66MZw==",
		Description:       "Comodo 'Mammoth' CT log", // b1N2rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RM=
		Url:               "mammoth.ct.comodo.com",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEi/8tkhjLRp0SXrlZdTzNkTd6HqmcmXiDJz3fAdWLgOhjmv4mohvRhwXul9bgW0ODgRwC9UGAgH/vpGHPvIS1qA==",
		Description:       "Cloudflare 'Nimbus2023' Log", // ejKMVNi3LbYg6jjgUh7phBZwMhOFTTvSK8E6V6NS61I=
		Url:               "ct.cloudflare.com/logs/nimbus2023",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAER+1MInu8Q39BwDZ5Rp9TwXhwm3ktvgJzpk/r7dDgGk7ZacMm3ljfcoIvP1E72T8jvyLT1bvdapylajZcTH6W5g==",
		Description:       "Google 'Xenon2021' log", // fT7y+I//iFVoJMLAyp5SiXkrxQ54CX8uapdomX4i8Nc=
		Url:               "ct.googleapis.com/logs/xenon2021",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzF05L2a4TH/BLgOhNKPoioYCrkoRxvcmajeb8Dj4XQmNY+gxa4Zmz3mzJTwe33i0qMVp+rfwgnliQ/bM/oFmhA==",
		Description:       "DigiCert Log Server 2", // h3W/51l8+IxDmV+9827/Vo1HVjb/SrVgwbTq/16ggw8=
		Url:               "ct2.digicert-ct.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAELsYzGMNwo8rBIlaklBIdmD2Ofn6HkfrjK0Ukz1uOIUC6Lm0jTITCXhoIdjs7JkyXnwuwYiJYiH7sE1YeKu8k9w==",
		Description:       "Let's Encrypt Oak 2021", // lCC8Ho7VjWyIcx+CiyIsDdHaTV5sT5Q9YdtOL1hNosI=
		Url:               "oak.ct.letsencrypt.org/2021",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1glwxqXsw2VqlAbHSeWbTthMGNIuACVn8Jj/jrnY2iN2uVUrEEwLj5VUCb+WF2XY44+mfUVYY7R/d8TIZ4olnw==",
		Description:       "Google 'Solera2021' log", // o8mYRegKt84AFXs3Qt8CB90nKytgLs+Y7iwS25xa5+c=
		Url:               "ct.googleapis.com/logs/solera2021",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0gBVBa3VR7QZu82V+ynXWD14JM3ORp37MtRxTmACJV5ZPtfUA7htQ2hofuigZQs+bnFZkje+qejxoyvk2Q1VaA==",
		Description:       "Google 'Argon2018' log", // pFASaQVaFVReYhGrN7wQP2KuVXakXksXFEU+GyIQaiU=
		Url:               "ct.googleapis.com/logs/argon2018",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfahLEimAoz2t01p3uMziiLOl/fHTDM0YDOhBRuiBARsV4UvxG2LdNgoIGLrtCzWE0J5APC2em4JlvR8EEEFMoA==",
		Description:       "Google 'Pilot' log", // pLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BA=
		Url:               "ct.googleapis.com/pilot",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEOfifIGLUV1Voou9JLfA5LZreRLSUMOCeeic8q3Dw0fpRkGMWV0Gtq20fgHQweQJeLVmEByQj9p81uIW4QkWkTw==",
		Description:       "Google 'Submariner' log", // qJnYeAySkKr0YvMYgMz71SRR6XDQ+/WR73Ww2ZtkVoE=
		Url:               "ct.googleapis.com/submariner",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEchY+C+/vzj5g3ZXLY3q5qY1Kb2zcYYCmRV4vg6yU84WI0KV00HuO/8XuQqLwLZPjwtCymeLhQunSxgAnaXSuzg==",
		Description:       "Google 'Xenon2023' log", // rfe++nz/EMiLnT2cHj4YarRnKV3PsQwkyoWGNOvcgoo=
		Url:               "ct.googleapis.com/logs/xenon2023",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEXu8iQwSCRSf2CbITGpUpBtFVt8+I0IU0d1C36Lfe1+fbwdaI0Z5FktfM2fBoI1bXBd18k2ggKGYGgdZBgLKTg==",
		Description:       "DigiCert Nessie 2023", // s3N3B+GEUPhjhtYFqdwRCUp5LbFnDAuH3PADDnk2pZo=
		Url:               "nessie2023.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEw8i8S7qiGEs9NXv0ZJFh6uuOmR2Q7dPprzk9XNNGkUXjzqx2SDvRfiwKYwBljfWujozHESVPQyydGaHhkaSz/g==",
		Description:       "Google 'Testtube' log", // sMyD5aX5fWuvfAnMKEkEhyrH6IsTLGNQt8b9JuFsbHc=
		Url:               "ct.googleapis.com/testtube",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1syJvwQdrv0a8dM2VAnK/SmHJNw/+FxC+CncFcnXMX2jNH9Xs7Q56FiV3taG5G2CokMsizhpcm7xXzuR3IHmag==",
		Description:       "Google 'Xenon2018' log", // sQzVWabWeEaBH335pRUyc5rEjXA76gMj2l04dVvArU4=
		Url:               "ct.googleapis.com/logs/xenon2018",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6Tx2p1yKY4015NyIYvdrk36es0uAc1zA4PQ+TGRY+3ZjUTIYY9Wyu+3q/147JG4vNVKLtDWarZwVqGkg6lAYzA==",
		Description:       "Google 'Argon2020' log", // sh4FzIuizYogTodm+Su5iiUgZ2va+nDnsklTLe+LkF4=
		Url:               "ct.googleapis.com/logs/argon2020",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEmyGDvYXsRJsNyXSrYc9DjHsIa2xzb4UR7ZxVoV6mrc9iZB7xjI6+NrOiwH+P/xxkRmOFG6Jel20q37hTh58rA==",
		Description:       "Google 'Skydiver' log", // u9nfvB+KcbWTlCOXqpJ7RzhXlQqrUugakJZkNo4e0YU=
		Url:               "ct.googleapis.com/skydiver",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEKATl2B3SAbxyzGOfNRB+AytNTGvdF/FFY6HzWb+/HPE4lJ37vx2nEm99KYUy9SoNzF5VyTwCQG5nL/c5Q77yQQ==",
		Description:       "Google 'Crucible' log", // w78Dp+HKiEHGB7rj/0Jw/KXsRbGG675OLPP8d4Yw9fY=
		Url:               "ct.googleapis.com/logs/crucible",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAESYlKFDLLFmA9JScaiaNnqlU8oWDytxIYMfswHy9Esg0aiX+WnP/yj4O0ViEHtLwbmOQeSWBGkIu9YK9CLeer+g==",
		Description:       "DigiCert Yeti 2018", // wRZK4Kdy0tQ5LcgKwQdw1PDEm96ZGkhAwfoHUWT2M2A=
		Url:               "yeti2018.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
	{
		Key:               "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4hHIyMVIrR9oShgbQMYEk8WX1lmkfFKB448Gn93KbsZnnwljDHY6MQqEnWfKGgMOq0gh3QK48c5ZB3UKSIFZ4g==",
		Description:       "DigiCert Nessie 2020", // xlKg7EjOs/yrFwmSxDqHQTMJ6ABlomJSQBujNioXxWU=
		Url:               "nessie2020.ct.digicert.com/log",
		MaximumMergeDelay: 86400,
	},
}
